javadoc:
	javadoc -sourcepath ../../PowerGrab/src/main/java/ -d ./web/ -subpackages uk.ac.ed.inf.powergrab:org.paulgeorgiou -private -doctitle PowerGrab -windowtitle "PowerGrab documentation"

clean:
	rm -r ./web/*
